module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/agentflow', '<rootDir>/tests', '<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'agentflow/**/*.ts',
    '!agentflow/**/*.d.ts',
    '!agentflow/**/*.interface.ts',
    '!agentflow/**/*.mock.ts',
    '!agentflow/index.ts',
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.mock.ts',
    '!src/index.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/agentflow/$1',
    '^@adapters/(.*)$': '<rootDir>/agentflow/adapters/$1',
    '^@core/(.*)$': '<rootDir>/agentflow/core/$1',
    '^@api/(.*)$': '<rootDir>/agentflow/api/$1',
    '^@monitoring/(.*)$': '<rootDir>/agentflow/monitoring/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  testTimeout: 30000,
  verbose: true,
};