apiVersion: v1
kind: ConfigMap
metadata:
  name: agentflow-api-config
  namespace: agentflow
  labels:
    app: agentflow-api
    component: config
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  CORS_ORIGINS: "https://agentflow.ai,https://www.agentflow.ai"
  RATE_LIMIT_WINDOW: "900000"
  RATE_LIMIT_MAX: "1000"
  HEALTH_CHECK_INTERVAL: "30"
  METRICS_ENABLED: "true"
  CACHE_TTL: "300"
  REQUEST_TIMEOUT: "30000"
  GRACEFUL_SHUTDOWN_TIMEOUT: "10000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agentflow-api-nginx-config
  namespace: agentflow
  labels:
    app: agentflow-api
    component: nginx
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream agentflow-api {
            server 127.0.0.1:3000;
        }
        
        server {
            listen 80;
            server_name _;
            
            location /health {
                proxy_pass http://agentflow-api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                access_log off;
            }
            
            location / {
                proxy_pass http://agentflow-api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_timeout 30s;
                proxy_connect_timeout 5s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
            }
        }
    }