apiVersion: v1
kind: Namespace
metadata:
  name: agentflow
  labels:
    name: agentflow
    environment: production
  annotations:
    description: "AgentFlow API namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: agentflow-quota
  namespace: agentflow
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: agentflow-limits
  namespace: agentflow
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container