apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agentflow-api-pdb
  namespace: agentflow
  labels:
    app: agentflow-api
    component: disruption-budget
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: agentflow-api
      version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: agentflow-api-metrics
  namespace: agentflow
  labels:
    app: agentflow-api
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: agentflow-api
    version: v1
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP