apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentflow-api.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentflow-api.labels" . | nindent 4 }}
    component: secrets
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
---
{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentflow-api.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentflow-api.labels" . | nindent 4 }}
    component: tls
type: kubernetes.io/tls
data:
  # Replace with actual TLS certificate and key
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
    # Add your TLS certificate here
    LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
    # Add your TLS private key here
    LS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==
{{- end }}