apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentflow-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentflow-api.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: api
  selector:
    {{- include "agentflow-api.selectorLabels" . | nindent 4 }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentflow-api.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentflow-api.labels" . | nindent 4 }}
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: metrics
  selector:
    {{- include "agentflow-api.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentflow-api.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentflow-api.labels" . | nindent 4 }}
    component: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: api
  selector:
    {{- include "agentflow-api.selectorLabels" . | nindent 4 }}